#ifndef LIBMARV_NAMESPACE_HPP
#define LIBMARV_NAMESPACE_HPP

#include <cuda/std/__cccl/preprocessor.h>


#define LIBMARV_NAMESPACE_BEGIN namespace libmarv{ 

#define LIBMARV_NAMESPACE_END }


#define LIBMARV_INLINE_NAMESPACE_BEGIN \
    inline namespace _CCCL_PP_SPLICE_WITH(_, SM, __CUDA_ARCH_LIST__){

#define LIBMARV_INLINE_NAMESPACE_END }


#define LIBMARV_NAMESPACE_WITH_NESTING_BEGIN \
    LIBMARV_NAMESPACE_BEGIN \
    LIBMARV_INLINE_NAMESPACE_BEGIN

#define LIBMARV_NAMESPACE_WITH_NESTING_END \
    LIBMARV_INLINE_NAMESPACE_END \
    LIBMARV_NAMESPACE_END
    


#endif